import { NotesData, QuizQuestion, SessionRecord } from '../types';

export const GRADIENT_DESCENT_NOTES: NotesData = {
  session_id: 'sn_gradient_descent',
  topic_title: 'Gradient Descent Optimization',
  subject_category: 'Machine Learning & Numerical Optimization',
  created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  source_contributions: [
    { source_id: 'S1', filename: 'ml_textbook_ch4_optimization.pdf', percentage: 42, statementCount: 15 },
    { source_id: 'S2', filename: 'mit_lecture_gradient_methods.pdf', percentage: 33, statementCount: 12 },
    { source_id: 'S3', filename: 'cs229_optimization_slides.pdf', percentage: 25, statementCount: 9 },
  ],
  faithfulness: {
    overall_score: 0.94,
    total_statements: 36,
    verified_statements: 34,
    flagged_count: 2,
    reliability_tier: 'Highly Reliable',
    flagged_statements: [
      {
        id: 'flag_1',
        statement: 'Neural networks were first trained via backpropagation with gradient descent in the early 1950s.',
        source_ids: ['S2'],
        faithfulness_score: 0.42,
        verdict: 'unsupported',
        issue: 'Source S2 mentions 1950s Perceptrons, but backpropagation gradient descent was formalized later in the 1970s/1980s.',
        suggestedCorrection: 'While the Perceptron was proposed in 1958, backpropagation using gradient descent for multi-layer networks gained widespread adoption following Rumelhart et al. in 1986.',
        status: 'pending',
      },
      {
        id: 'flag_2',
        statement: 'The optimal default learning rate for Batch Gradient Descent across all continuous loss functions is consistently 0.01.',
        source_ids: ['S1', 'S3'],
        faithfulness_score: 0.58,
        verdict: 'neutral',
        issue: 'S1 designates 0.01 as a standard empirical toy default, while S3 emphasizes that the optimal learning rate strictly depends on the Lipschitz constant of the gradient.',
        suggestedCorrection: '0.01 is often used as an empirical starting heuristic, though hyperparameter tuning or adaptive step sizes (such as AdaGrad/Adam) are theoretically required based on the Hessian curvature.',
        status: 'pending',
      },
    ],
  },
  terminology_map: [
    {
      id: 'term_1',
      canonical: 'Gradient Descent',
      definition: 'A first-order iterative optimization algorithm for finding a local minimum of a differentiable function.',
      variants: [
        { term: 'Steepest Descent', source_id: 'S1', frequency: 14 },
        { term: 'Gradient Method', source_id: 'S2', frequency: 8 },
        { term: 'First-Order Optimizer', source_id: 'S3', frequency: 5 },
      ],
    },
    {
      id: 'term_2',
      canonical: 'Learning Rate (η)',
      definition: 'A tuning hyperparameter that determines the step size at each iteration while moving toward a minimum.',
      variants: [
        { term: 'Step Size (α)', source_id: 'S2', frequency: 19 },
        { term: 'Update Scale parameter', source_id: 'S3', frequency: 4 },
      ],
    },
    {
      id: 'term_3',
      canonical: 'Objective Function',
      definition: 'The real-valued function J(θ) to be minimized during parameter estimation.',
      variants: [
        { term: 'Cost Function', source_id: 'S1', frequency: 22 },
        { term: 'Loss / Criterion', source_id: 'S3', frequency: 16 },
      ],
    },
    {
      id: 'term_4',
      canonical: 'Stochastic Gradient Descent (SGD)',
      definition: 'Optimization variant updating parameters using the gradient of a single randomly chosen training sample per step.',
      variants: [
        { term: 'Online Gradient Descent', source_id: 'S1', frequency: 9 },
        { term: 'Incremental Gradient Method', source_id: 'S2', frequency: 7 },
      ],
    },
  ],
  detailed_sections: [
    {
      heading: '1. Foundational Concept & Mathematical Mechanics',
      statements: [
        {
          id: 'ds_1',
          text: 'Gradient descent is a first-order optimization algorithm designed to minimize a scalar-valued differentiable loss function J(θ) by iteratively taking steps proportional to the negative of the gradient at the current parameter position.',
          source_ids: ['S1', 'S2'],
          faithfulness_score: 0.98,
        },
        {
          id: 'ds_2',
          text: 'Because the gradient vector ∇J(θ) points in the direction of greatest instantaneous increase of the function, negating the vector guarantees a local direction of steepest decrease for infinitesimal step displacements.',
          source_ids: ['S1', 'S3'],
          faithfulness_score: 0.96,
        },
        {
          id: 'ds_3',
          text: 'The standard update equation is parameterized as θ_{t+1} = θ_t - η ∇J(θ_t), where η represents the learning rate (or step size α in lecture notation).',
          source_ids: ['S1', 'S2', 'S3'],
          faithfulness_score: 0.99,
        },
      ],
    },
    {
      heading: '2. Variants: Batch, Stochastic, and Mini-Batch',
      statements: [
        {
          id: 'ds_4',
          text: 'Standard Batch Gradient Descent computes the exact gradient across the entire training dataset of N examples before performing a single parameter update, producing stable convergence trajectories but incurring prohibitive computational cost O(N·d) per epoch.',
          source_ids: ['S1', 'S3'],
          faithfulness_score: 0.95,
        },
        {
          id: 'ds_5',
          text: 'Stochastic Gradient Descent (SGD) drastically accelerates computation by estimating the gradient from a single randomly selected sample i ∈ {1,...,N}, causing noisy parameter updates that can help escape shallow saddle points and local minima.',
          source_ids: ['S2', 'S3'],
          faithfulness_score: 0.93,
        },
        {
          id: 'ds_6',
          text: 'Mini-batch Gradient Descent serves as the industry compromise, sampling a subset B (typically between 32 and 512 instances) to exploit vectorization on modern GPU hardware while preserving variance reduction.',
          source_ids: ['S1', 'S2'],
          faithfulness_score: 0.97,
        },
      ],
    },
    {
      heading: '3. Convergence Challenges, Condition Number & Momentum',
      statements: [
        {
          id: 'ds_7',
          text: 'When the objective function exhibits ill-conditioned curvature (high condition number of the Hessian matrix H), standard gradient descent oscillates transversally across steep ravines rather than progressing along the flatter optimal valley floor.',
          source_ids: ['S1', 'S2'],
          faithfulness_score: 0.94,
        },
        {
          id: 'ds_8',
          text: 'Classical Momentum dampens these perpendicular oscillations by accumulating an exponential moving average of past gradients: v_t = γ v_{t-1} + η ∇J(θ_t), where γ ∈ [0.9, 0.99] acts as a friction parameter.',
          source_ids: ['S2', 'S3'],
          faithfulness_score: 0.96,
        },
        {
          id: 'ds_9',
          text: 'Nesterov Accelerated Gradient (NAG) improves upon standard momentum by computing the prospective gradient at the look-ahead position θ_t - γ v_{t-1}, enabling an anticipatory braking effect.',
          source_ids: ['S1', 'S3'],
          faithfulness_score: 0.92,
        },
      ],
    },
  ],
  bullet_notes: [
    {
      id: 'bn_1',
      label: 'Core Definition',
      text: 'First-order iterative numerical optimizer that drives parameters θ toward a local or global minimum of loss function J(θ) along the negative gradient vector.',
      source_ids: ['S1', 'S2'],
      importance: 'critical',
    },
    {
      id: 'bn_2',
      label: 'Update Equation',
      text: 'θ_{t+1} = θ_t - η · ∇J(θ_t), with step size η > 0 controlling displacement magnitude.',
      source_ids: ['S1', 'S3'],
      importance: 'critical',
    },
    {
      id: 'bn_3',
      label: 'Batch vs SGD Comparison',
      text: 'Batch GD uses all N samples (deterministic, smooth, memory-intensive); SGD uses 1 sample (stochastic, fast, noisy updates); Mini-batch uses b samples (GPU parallel friendly).',
      source_ids: ['S1', 'S2', 'S3'],
      importance: 'high',
    },
    {
      id: 'bn_4',
      label: 'Learning Rate Dynamics',
      text: 'Too small η leads to agonizingly slow convergence; too large η triggers oscillation and catastrophic numerical divergence.',
      source_ids: ['S2', 'S3'],
      importance: 'high',
    },
    {
      id: 'bn_5',
      label: 'Ill-Conditioned Ravines',
      text: 'Occurs when eigenvalues of the Hessian satisfy λ_max >> λ_min, causing zig-zagging orthogonal to the optimal descent path.',
      source_ids: ['S1', 'S2'],
      importance: 'medium',
    },
    {
      id: 'bn_6',
      label: 'Exam High-Yield Pitfall',
      text: 'Standard gradient descent guarantees convergence to the global minimum ONLY for strictly convex functions; non-convex deep loss landscapes can trap iterates in saddle points.',
      source_ids: ['S1', 'S3'],
      importance: 'critical',
    },
  ],
};

export const GRADIENT_DESCENT_QUIZ: QuizQuestion[] = [
  {
    id: 'q_1',
    type: 'mcq',
    question: 'In textbook literature (S1), which terminology is frequently used interchangeably with "Gradient Descent"?',
    options: ['Backpropagation', 'Steepest Descent', 'Pushdown Automaton', 'Newton-Raphson Method'],
    correct_answer: 'Steepest Descent',
    explanation: 'As identified in the Terminology Map, S1 explicitly designates the algorithm as "Steepest Descent" because the negative gradient represents the direction of maximum instantaneous rate of decrease.',
    source_reference: 'S1: ml_textbook_ch4_optimization.pdf',
  },
  {
    id: 'q_2',
    type: 'mcq',
    question: 'Why does standard Batch Gradient Descent become impractical on massive modern datasets?',
    options: [
      'It cannot guarantee mathematical convergence on convex surfaces.',
      'It requires computing gradients across all N training samples prior to every single parameter update.',
      'It always oscillates into negative loss space.',
      'It cannot be computed using first-order derivatives.',
    ],
    correct_answer: 'It requires computing gradients across all N training samples prior to every single parameter update.',
    explanation: 'Batch GD computes the full gradient over the complete dataset of size N for each update step, causing each epoch to take O(N·d) operations.',
    source_reference: 'S1 & S3',
  },
  {
    id: 'q_3',
    type: 'fill_in_the_blank',
    question: 'The parameter update formula in gradient descent is θ_{t+1} = θ_t - η · ________, representing the vector of partial derivatives.',
    prefixText: 'The gradient vector is denoted as',
    correct_answer: '∇J(θ_t)',
    acceptable_alternatives: ['gradient', 'grad J', 'nabla J', '∇J(θ)'],
    explanation: '∇J(θ_t) represents the gradient (vector of first-order partial derivatives) evaluated at the current parameter estimates.',
    source_reference: 'S1, S2, S3',
  },
  {
    id: 'q_4',
    type: 'short_answer',
    question: 'Briefly explain why terminology normalization is critical when consolidating multiple study resources on optimization.',
    sample_answer: 'Different textbooks and professors use divergent notations for the identical concept-such as "step size α" vs "learning rate η", or "cost function J(θ)" vs "objective criterion L(w)". Without normalization, notes create cognitive friction and false distinctions.',
    key_points: [
      'Resolves notation discrepancies (α vs η, J(θ) vs Loss)',
      'Prevents confusing identical mathematical algorithms as distinct techniques',
      'Harmonizes canonical vocabulary for unified exam revision',
    ],
    explanation: 'Terminology normalization ensures students study a single canonical vocabulary without second-guessing semantic synonyms.',
    source_reference: 'Terminology Map Synthesis',
  },
  {
    id: 'q_5',
    type: 'long_answer',
    question: 'Compare Batch Gradient Descent, Stochastic Gradient Descent (SGD), and Mini-Batch Gradient Descent across computational efficiency, trajectory stability, and susceptibility to local minima.',
    sample_answer: 'Batch GD computes the exact gradient over all N examples, producing a smooth and deterministic descent path toward the minimum, but with high computational latency O(N·d). SGD updates parameters per single random example, yielding rapid iterations and noisy fluctuations that assist in escaping shallow local minima and saddle points, though final convergence wanders around the minimum. Mini-batch GD balances both approaches by utilizing batch sizes (e.g. 32-256), leveraging SIMD/GPU tensor acceleration while smoothing variance.',
    rubric_criteria: [
      { criterion: 'Clear contrast of batch sizes and per-step computational cost', weight: 30 },
      { criterion: 'Explanation of gradient variance and trajectory smoothness', weight: 30 },
      { criterion: 'Analysis of local minima / saddle point escape mechanisms', weight: 20 },
      { criterion: 'Practical modern hardware justification (GPU mini-batching)', weight: 20 },
    ],
    explanation: 'A comprehensive comparative analysis grounded in Section 2 of the synthesized notes.',
    source_reference: 'S1, S2, S3',
  },
];

export const INITIAL_PRESET_SESSIONS: SessionRecord[] = [
  {
    session_id: 'sn_gradient_descent',
    title: 'Gradient Descent Optimization',
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    status: 'completed',
    faithfulness_score: 0.94,
    sources: [
      { source_id: 'S1', filename: 'ml_textbook_ch4_optimization.pdf', size: 3240000, type: 'pdf', status: 'ready', wordCount: 8400, contributionPercent: 42 },
      { source_id: 'S2', filename: 'mit_lecture_gradient_methods.pdf', size: 980000, type: 'pdf', status: 'ready', wordCount: 4200, contributionPercent: 33 },
      { source_id: 'S3', filename: 'cs229_optimization_slides.pdf', size: 1450000, type: 'pdf', status: 'ready', wordCount: 2900, contributionPercent: 25 },
    ],
    validation: {
      valid: true,
      topic_overlap_score: 0.94,
      status: 'valid',
      message: 'All 3 documents extracted successfully and demonstrate high conceptual topic compatibility on first-order optimization.',
      detectedTopic: 'Machine Learning Optimization & Gradient Methods',
      keySharedTerms: ['Gradient Descent', 'Learning Rate', 'Convexity', 'Hessian Matrix', 'Loss Function'],
    },
    notes: GRADIENT_DESCENT_NOTES,
    quiz: GRADIENT_DESCENT_QUIZ,
  },
  {
    session_id: 'sn_cell_division',
    title: 'Cell Division: Mitosis & Meiosis',
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    status: 'completed',
    faithfulness_score: 0.91,
    sources: [
      { source_id: 'S1', filename: 'campbell_biology_ch12_cell_cycle.pdf', size: 4120000, type: 'pdf', status: 'ready', wordCount: 9500, contributionPercent: 45 },
      { source_id: 'S2', filename: 'medical_genetics_lecture_notes.pdf', size: 1200000, type: 'pdf', status: 'ready', wordCount: 5100, contributionPercent: 35 },
      { source_id: 'S3', filename: 'meiosis_cytogenetics_summary.txt', size: 240000, type: 'txt', status: 'ready', wordCount: 2200, contributionPercent: 20 },
    ],
    validation: {
      valid: true,
      topic_overlap_score: 0.91,
      status: 'valid',
      message: 'Sources show strong alignment across somatic vs gametic division pathways.',
      detectedTopic: 'Cellular Cycle & Cytogenetics',
      keySharedTerms: ['Mitosis', 'Meiosis', 'Kinetochore', 'Crossing Over', 'Homologous Chromosomes'],
    },
  },
  {
    session_id: 'sn_indian_polity',
    title: 'Indian Polity: Fundamental Rights',
    created_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    status: 'completed',
    faithfulness_score: 0.96,
    sources: [
      { source_id: 'S1', filename: 'laxmikanth_constitution_part3.pdf', size: 5400000, type: 'pdf', status: 'ready', wordCount: 14200, contributionPercent: 48 },
      { source_id: 'S2', filename: 'supreme_court_landmark_cases.pdf', size: 2100000, type: 'pdf', status: 'ready', wordCount: 6800, contributionPercent: 32 },
      { source_id: 'S3', filename: 'governance_prelims_revision.txt', size: 380000, type: 'txt', status: 'ready', wordCount: 3900, contributionPercent: 20 },
    ],
    validation: {
      valid: true,
      topic_overlap_score: 0.96,
      status: 'valid',
      message: 'Comprehensive statutory and jurisprudence overlap on Articles 12-35.',
      detectedTopic: 'Constitutional Law & Fundamental Rights',
      keySharedTerms: ['Article 21', 'Basic Structure Doctrine', 'Writs', 'Judicial Review', 'Right to Equality'],
    },
  },
  {
    session_id: 'sn_thermodynamics',
    title: 'Thermodynamics & Statistical Mechanics',
    created_at: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
    status: 'completed',
    faithfulness_score: 0.88,
    sources: [
      { source_id: 'S1', filename: 'callen_thermodynamics_principles.pdf', size: 3800000, type: 'pdf', status: 'ready', wordCount: 7600, contributionPercent: 55 },
      { source_id: 'S2', filename: 'mit_8044_statistical_thermo.pdf', size: 1900000, type: 'pdf', status: 'ready', wordCount: 4900, contributionPercent: 45 },
    ],
    validation: {
      valid: true,
      topic_overlap_score: 0.88,
      status: 'valid',
      message: 'Compatible multi-source study material covering macroscopic and microscopic entropy formulations.',
      detectedTopic: 'Thermal Physics & State Functions',
      keySharedTerms: ['Entropy', 'Enthalpy', 'Carnot Cycle', 'Microstates', 'Free Energy'],
    },
  },
  {
    session_id: 'sn_modern_history',
    title: 'Modern Indian History: Freedom Struggle',
    created_at: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
    status: 'completed',
    faithfulness_score: 0.92,
    sources: [
      { source_id: 'S1', filename: 'spectrum_modern_india_freedom_struggle.pdf', size: 4800000, type: 'pdf', status: 'ready', wordCount: 12100, contributionPercent: 50 },
      { source_id: 'S2', filename: 'bipan_chandra_national_movement.pdf', size: 3200000, type: 'pdf', status: 'ready', wordCount: 8800, contributionPercent: 30 },
      { source_id: 'S3', filename: 'ncert_history_themes3.pdf', size: 1750000, type: 'pdf', status: 'ready', wordCount: 4500, contributionPercent: 20 },
    ],
    validation: {
      valid: true,
      topic_overlap_score: 0.92,
      status: 'valid',
      message: 'Compatible historical chronology spanning 1885 to 1947.',
      detectedTopic: 'Modern History & National Movements',
      keySharedTerms: ['Non-Cooperation', 'Civil Disobedience', 'Quit India', 'Round Table Conferences'],
    },
  },
];
